/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import EntityManager.EntityManagerUtil;
import java.util.HashMap;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.bean.Atividade;
import modelo.bean.OrganizaPrev;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mateus
 */
public class FormCadastroOrganizaPrev extends javax.swing.JDialog {
boolean editando;
    /**
     * Creates new form FormCadastroOrganizaPrev
     */
    public FormCadastroOrganizaPrev(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("UrcampEventoEextensaoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("from OrganizaPrev order by envolvidos");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        queryAtv = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("from Atividade order by tipoAtividade");
        listAtv = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(queryAtv.getResultList());
        jButtonFechar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox011 = new javax.swing.JCheckBox();
        jCheckBox018 = new javax.swing.JCheckBox();
        jCheckBox013 = new javax.swing.JCheckBox();
        jCheckBox014 = new javax.swing.JCheckBox();
        jCheckBox012 = new javax.swing.JCheckBox();
        jCheckBox028 = new javax.swing.JCheckBox();
        jCheckBox026 = new javax.swing.JCheckBox();
        jCheckBox027 = new javax.swing.JCheckBox();
        jCheckBox021 = new javax.swing.JCheckBox();
        jCheckBox110 = new javax.swing.JCheckBox();
        jCheckBox07 = new javax.swing.JCheckBox();
        jCheckBox019 = new javax.swing.JCheckBox();
        jCheckBox08 = new javax.swing.JCheckBox();
        jCheckBox015 = new javax.swing.JCheckBox();
        jCheckBox022 = new javax.swing.JCheckBox();
        jCheckBox020 = new javax.swing.JCheckBox();
        jCheckBox016 = new javax.swing.JCheckBox();
        jCheckBox023 = new javax.swing.JCheckBox();
        jCheckBox024 = new javax.swing.JCheckBox();
        jCheckBox06 = new javax.swing.JCheckBox();
        jCheckBox025 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEnvo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox036 = new javax.swing.JCheckBox();
        jCheckBox033 = new javax.swing.JCheckBox();
        jCheckBox034 = new javax.swing.JCheckBox();
        jCheckBox035 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox029 = new javax.swing.JCheckBox();
        jCheckBox031 = new javax.swing.JCheckBox();
        jCheckBox030 = new javax.swing.JCheckBox();
        jCheckBox032 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDisc = new javax.swing.JTextField();
        jCheckBox09 = new javax.swing.JCheckBox();
        jTextFieldExt = new javax.swing.JTextField();
        jTextFieldOrgPrev = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAcces = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButtonGravar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrga = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        JcbxOrdenar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFiltro = new javax.swing.JTextField();
        jButtonFiltrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462403813_close.png"))); // NOI18N
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.green)); // NOI18N

        jCheckBox2.setText("NEAD/Moodle");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("canetas quadro branco/apagador");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Reserva salas adequadas");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Som");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("Operador de recursos audiovisuais");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox011.setText("Vídeo institucional");
        jCheckBox011.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox011ActionPerformed(evt);
            }
        });

        jCheckBox018.setText("Reserva de hotel (se professor externo)");
        jCheckBox018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox018ActionPerformed(evt);
            }
        });

        jCheckBox013.setText("Solicitação de diárias/deslocamento");
        jCheckBox013.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox013ActionPerformed(evt);
            }
        });

        jCheckBox014.setText("Certificado dos palestrantes");
        jCheckBox014.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox014ActionPerformed(evt);
            }
        });

        jCheckBox012.setText("Cerimonial");
        jCheckBox012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox012ActionPerformed(evt);
            }
        });

        jCheckBox028.setText("Organização e composição da mesa");
        jCheckBox028.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox028ActionPerformed(evt);
            }
        });

        jCheckBox026.setText("Decoração");
        jCheckBox026.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox026ActionPerformed(evt);
            }
        });

        jCheckBox027.setText("Coffee break");
        jCheckBox027.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox027ActionPerformed(evt);
            }
        });

        jCheckBox021.setText("Banner da URCAMP");
        jCheckBox021.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox021ActionPerformed(evt);
            }
        });

        jCheckBox110.setText("Identificação da equipe organizadora (crachás)");
        jCheckBox110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox110ActionPerformed(evt);
            }
        });

        jCheckBox07.setText("Texto de apresentação dos anais");
        jCheckBox07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox07ActionPerformed(evt);
            }
        });

        jCheckBox019.setText("Cobertura assessoria de imprensa");
        jCheckBox019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox019ActionPerformed(evt);
            }
        });

        jCheckBox08.setText("Instrumento de avaliação (pedagógica e satisfação)");
        jCheckBox08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox08ActionPerformed(evt);
            }
        });

        jCheckBox015.setText("Espaço para parceiros");
        jCheckBox015.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox015ActionPerformed(evt);
            }
        });

        jCheckBox022.setText("Estrutura para exposições");
        jCheckBox022.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox022ActionPerformed(evt);
            }
        });

        jCheckBox020.setText("Iluminação específica");
        jCheckBox020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox020ActionPerformed(evt);
            }
        });

        jCheckBox016.setText("Impressão de diário");
        jCheckBox016.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox016ActionPerformed(evt);
            }
        });

        jCheckBox023.setText("Brindes");
        jCheckBox023.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox023ActionPerformed(evt);
            }
        });

        jCheckBox024.setText("Coquetel");
        jCheckBox024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox024ActionPerformed(evt);
            }
        });

        jCheckBox06.setText("Colocação de Faixas");
        jCheckBox06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox06ActionPerformed(evt);
            }
        });

        jCheckBox025.setText("Café e água");
        jCheckBox025.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox025ActionPerformed(evt);
            }
        });

        jLabel3.setText("Discursos (quem?):");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableOrga, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.envolvidos}"), jTextFieldEnvo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldEnvo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEnvoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEnvoFocusLost(evt);
            }
        });
        jTextFieldEnvo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEnvoKeyTyped(evt);
            }
        });

        jLabel2.setText("Envolvidos na abertura:");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Hinos"));

        jCheckBox036.setText("País do visitante/palestrante");
        jCheckBox036.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox036ActionPerformed(evt);
            }
        });

        jCheckBox033.setText("Nacional");
        jCheckBox033.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox033ActionPerformed(evt);
            }
        });

        jCheckBox034.setText("Bagé");
        jCheckBox034.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox034ActionPerformed(evt);
            }
        });

        jCheckBox035.setText("Rio Grande do Sul");
        jCheckBox035.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox035ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox033)
                    .addComponent(jCheckBox034))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox036)
                    .addComponent(jCheckBox035)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox033)
                    .addComponent(jCheckBox035))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox034)
                    .addComponent(jCheckBox036)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Bandeiras"));

        jCheckBox029.setText("Nacional");
        jCheckBox029.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox029ActionPerformed(evt);
            }
        });

        jCheckBox031.setText("Cidade");
        jCheckBox031.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox031ActionPerformed(evt);
            }
        });

        jCheckBox030.setText("RS");
        jCheckBox030.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox030ActionPerformed(evt);
            }
        });

        jCheckBox032.setText("URCAMP");
        jCheckBox032.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox032ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox029)
                    .addComponent(jCheckBox030))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox032)
                    .addComponent(jCheckBox031))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox029)
                    .addComponent(jCheckBox031))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox032)
                    .addComponent(jCheckBox030)))
        );

        jCheckBox1.setText("Ambiente virtual para inscrição, submissão e avaliação de trabalhos");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Estrutura complementar externa:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableOrga, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.discurso}"), jTextFieldDisc, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldDisc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDiscFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDiscFocusLost(evt);
            }
        });
        jTextFieldDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDiscKeyTyped(evt);
            }
        });

        jCheckBox09.setText("Estrutura para apresentação de trabalhos");
        jCheckBox09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox09ActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableOrga, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.extruturaex}"), jTextFieldExt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldExt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldExtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldExtFocusLost(evt);
            }
        });
        jTextFieldExt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldExtKeyTyped(evt);
            }
        });

        jTextFieldOrgPrev.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableOrga, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.necessidade}"), jTextFieldOrgPrev, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel5.setText("Alunos com necessidades especiais de acessibilidade:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableOrga, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.alunosespc}"), jTextFieldAcces, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldAcces.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAccesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAccesFocusLost(evt);
            }
        });
        jTextFieldAcces.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAccesKeyTyped(evt);
            }
        });

        jLabel6.setText("Atividade:");

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listAtv, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableOrga, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.atividade}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });

        jButton1.setText("Atividades");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.green)); // NOI18N
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462402262_BT_save.png"))); // NOI18N
        jButtonGravar.setToolTipText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonGravar);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462402370_editor-trash-delete-recycle-bin-glyph.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonExcluir);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462402556_add.png"))); // NOI18N
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonNovo);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462402761_cancel-2.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonCancelar);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462403685_broom_stick_3.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jPanel8.add(jButtonLimpar);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462403130_update.png"))); // NOI18N
        jButtonEditar.setToolTipText("Alterar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonEditar);

        jButton2.setText("Pós execução");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox2)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jCheckBox5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox06))
                                    .addComponent(jCheckBox07)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox08)
                                    .addComponent(jCheckBox09)
                                    .addComponent(jCheckBox110, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox020)
                                    .addComponent(jCheckBox011)
                                    .addComponent(jCheckBox016)
                                    .addComponent(jCheckBox018)
                                    .addComponent(jCheckBox015)
                                    .addComponent(jCheckBox014)
                                    .addComponent(jCheckBox013)
                                    .addComponent(jCheckBox012)
                                    .addComponent(jCheckBox019)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(319, 319, 319)
                                .addComponent(jLabel6)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAcces, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox023)
                        .addComponent(jCheckBox024)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox026)
                                        .addComponent(jCheckBox027, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(61, 61, 61)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jCheckBox025)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4)))
                            .addGap(2, 2, 2)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldExt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDisc, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEnvo))))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBox021, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox022, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldOrgPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jCheckBox028, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox021, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(7, 7, 7)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox06))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox07)
                            .addComponent(jCheckBox016))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox08)
                            .addComponent(jCheckBox018))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox09)
                            .addComponent(jCheckBox019))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox110)
                            .addComponent(jCheckBox020))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldAcces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldEnvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox011)
                                    .addComponent(jCheckBox022))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox012, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox023))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox024)
                                    .addComponent(jCheckBox013))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox025)
                                    .addComponent(jCheckBox014)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBox026)
                                            .addComponent(jCheckBox015))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox027)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox028)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldOrgPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, jTableOrga);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${necessidade}"));
        columnBinding.setColumnName("Necessidade");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${alunosespc}"));
        columnBinding.setColumnName("Alunosespc");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${discurso}"));
        columnBinding.setColumnName("Discurso");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${envolvidos}"));
        columnBinding.setColumnName("Envolvidos");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${atividade}"));
        columnBinding.setColumnName("Atividade");
        columnBinding.setColumnClass(modelo.bean.Atividade.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${extruturaex}"));
        columnBinding.setColumnName("Extruturaex");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableOrga);

        jLabel8.setText("Ordem:");

        JcbxOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Envolvidos", "Discurso" }));
        JcbxOrdenar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JcbxOrdenarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JcbxOrdenarFocusLost(evt);
            }
        });

        jLabel9.setText("Filtro:");

        jTextFieldFiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFiltroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFiltroFocusLost(evt);
            }
        });

        jButtonFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462404504_filter.png"))); // NOI18N
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        jMenu1.setText("Relatorios");

        jMenuItem1.setText("Organizões prévias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Próxima página");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3)
                        .addComponent(JcbxOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(JcbxOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jButtonFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int linhaClicada = jTableOrga.getSelectedRow();
        if(linhaClicada < 0){
            JOptionPane.showMessageDialog(null, "Selecione um campo para editar!");
        }else{
            editando = true;
            trataEdicao();
          //  jTextFieldNecAtv.requestFocus();
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        editando = false;
        trataEdicao();
        atualizaGrid();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        list.add((OrganizaPrev) new OrganizaPrev());
        int row = list.size() -1;
        jTableOrga.setRowSelectionInterval(row, row);
        editando = true;
        trataEdicao();
       // jTextFieldNecAtv.requestFocus();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if(validaCampos()){
            try{
                int linhaClicada = jTableOrga.getSelectedRow();
                OrganizaPrev obj = list.get(linhaClicada);
                entityManager.getTransaction().begin();
                entityManager.remove(obj);
                entityManager.getTransaction().commit();
                editando = false;
                trataEdicao();
                atualizaGrid();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro ao gravar" + e.getMessage());
                if(entityManager.getTransaction().isActive()==false){
                    entityManager.getTransaction().begin();
                }
                entityManager.getTransaction().rollback();
                editando = false;
                atualizaGrid();
                trataEdicao();
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        if(validaCampos()){
            try{
                int linhaClicada = jTableOrga.getSelectedRow();
                OrganizaPrev obj = list.get(linhaClicada);
                entityManager.getTransaction().begin();
                entityManager.persist(obj);
                entityManager.getTransaction().commit();
                editando = false;
                trataEdicao();
                atualizaGrid();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro ao gravar" + e.getMessage());
                if(entityManager.getTransaction().isActive()==false){
                    entityManager.getTransaction().begin();
                }
                entityManager.getTransaction().rollback();
                editando = false;
                atualizaGrid();
                trataEdicao();
            }
        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
      pegaValorCheck();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
      pegaValorCheck();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox06ActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBox06ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox07ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox07ActionPerformed

    private void jCheckBox08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox08ActionPerformed
      pegaValorCheck();
    }//GEN-LAST:event_jCheckBox08ActionPerformed

    private void jCheckBox09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox09ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox09ActionPerformed

    private void jCheckBox110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox110ActionPerformed
      pegaValorCheck();
    }//GEN-LAST:event_jCheckBox110ActionPerformed

    private void jCheckBox011ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox011ActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBox011ActionPerformed

    private void jCheckBox012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox012ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox012ActionPerformed

    private void jCheckBox013ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox013ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox013ActionPerformed

    private void jCheckBox014ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox014ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox014ActionPerformed

    private void jCheckBox015ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox015ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox015ActionPerformed

    private void jCheckBox016ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox016ActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBox016ActionPerformed

    private void jCheckBox018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox018ActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBox018ActionPerformed

    private void jCheckBox019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox019ActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBox019ActionPerformed

    private void jCheckBox020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox020ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox020ActionPerformed

    private void jCheckBox021ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox021ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox021ActionPerformed

    private void jCheckBox022ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox022ActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBox022ActionPerformed

    private void jCheckBox023ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox023ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox023ActionPerformed

    private void jCheckBox024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox024ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox024ActionPerformed

    private void jCheckBox025ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox025ActionPerformed
      pegaValorCheck();
    }//GEN-LAST:event_jCheckBox025ActionPerformed

    private void jCheckBox026ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox026ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox026ActionPerformed

    private void jCheckBox027ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox027ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox027ActionPerformed

    private void jCheckBox028ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox028ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox028ActionPerformed

    private void jCheckBox029ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox029ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox029ActionPerformed

    private void jCheckBox030ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox030ActionPerformed
      pegaValorCheck();
    }//GEN-LAST:event_jCheckBox030ActionPerformed

    private void jCheckBox031ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox031ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox031ActionPerformed

    private void jCheckBox032ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox032ActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBox032ActionPerformed

    private void jCheckBox033ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox033ActionPerformed
      pegaValorCheck();
    }//GEN-LAST:event_jCheckBox033ActionPerformed

    private void jCheckBox034ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox034ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox034ActionPerformed

    private void jCheckBox035ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox035ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox035ActionPerformed

    private void jCheckBox036ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox036ActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBox036ActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jTextFieldDiscFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDiscFocusGained
     Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldDiscFocusGained

    private void jTextFieldDiscFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDiscFocusLost
      Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldDiscFocusLost

    private void jTextFieldEnvoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnvoFocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldEnvoFocusGained

    private void jTextFieldEnvoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEnvoFocusLost
      Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldEnvoFocusLost

    private void jTextFieldExtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldExtFocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldExtFocusGained

    private void jTextFieldExtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldExtFocusLost
       Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldExtFocusLost

    private void jTextFieldAccesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccesFocusGained
        Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldAccesFocusGained

    private void jTextFieldAccesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccesFocusLost
      Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldAccesFocusLost

    private void JcbxOrdenarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JcbxOrdenarFocusGained
        Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_JcbxOrdenarFocusGained

    private void JcbxOrdenarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JcbxOrdenarFocusLost
        Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_JcbxOrdenarFocusLost

    private void jTextFieldFiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFiltroFocusGained
      Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldFiltroFocusGained

    private void jTextFieldFiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFiltroFocusLost
       Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldFiltroFocusLost

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
      Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
       Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jTextFieldDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDiscKeyTyped
        Utilitarias.Uteis.limitaTamanhoCampo(evt, 40);
    }//GEN-LAST:event_jTextFieldDiscKeyTyped

    private void jTextFieldEnvoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnvoKeyTyped
       Utilitarias.Uteis.limitaTamanhoCampo(evt, 100);
    }//GEN-LAST:event_jTextFieldEnvoKeyTyped

    private void jTextFieldExtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldExtKeyTyped
      Utilitarias.Uteis.limitaTamanhoCampo(evt, 100);
    }//GEN-LAST:event_jTextFieldExtKeyTyped

    private void jTextFieldAccesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAccesKeyTyped
       Utilitarias.Uteis.limitaTamanhoCampo(evt, 100);
    }//GEN-LAST:event_jTextFieldAccesKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      JDialog form = new FormCadastroAtividades(null, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Cadastro De Atividades");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(Utilitarias.Uteis.confirmar("Você já terminou o seu registro?")){
        JDialog form = new FormCadastroPosExec(null, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Pós execução");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        JDialog form = new FormCadastroPosExec(null, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Pós execução");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
		    EntityManager em = EntityManagerUtil.getEntityManager();
		    List<OrganizaPrev> lista = em.createQuery("from OrganizaPrev").getResultList();
		    HashMap<String, Object> parametros = new HashMap<String, Object>();
		    String relatorio = "/../home/mateus/Documentos/ATI/UrcampEventoEextensao/reportOrganizacaoPrevia.jasper";
		    JRDataSource dataSource = new JRBeanCollectionDataSource(lista);
		    JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, dataSource);
		    JDialog viewer = new JDialog(new javax.swing.JFrame(), "Visualização do Relátorio", true);
		    viewer.setSize(1024, 768);
		    viewer.setLocationRelativeTo(null);
		    JasperViewer jrviewer = new JasperViewer(impressao, true);
		    viewer.getContentPane().add(jrviewer.getContentPane());
		    viewer.setVisible(true);
		} catch (JRException ex) {
		    System.out.print("Erro: " + ex.getMessage());
                }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroOrganizaPrev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroOrganizaPrev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroOrganizaPrev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroOrganizaPrev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCadastroOrganizaPrev dialog = new FormCadastroOrganizaPrev(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbxOrdenar;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JCheckBox jCheckBox011;
    private javax.swing.JCheckBox jCheckBox012;
    private javax.swing.JCheckBox jCheckBox013;
    private javax.swing.JCheckBox jCheckBox014;
    private javax.swing.JCheckBox jCheckBox015;
    private javax.swing.JCheckBox jCheckBox016;
    private javax.swing.JCheckBox jCheckBox018;
    private javax.swing.JCheckBox jCheckBox019;
    private javax.swing.JCheckBox jCheckBox020;
    private javax.swing.JCheckBox jCheckBox021;
    private javax.swing.JCheckBox jCheckBox022;
    private javax.swing.JCheckBox jCheckBox023;
    private javax.swing.JCheckBox jCheckBox024;
    private javax.swing.JCheckBox jCheckBox025;
    private javax.swing.JCheckBox jCheckBox026;
    private javax.swing.JCheckBox jCheckBox027;
    private javax.swing.JCheckBox jCheckBox028;
    private javax.swing.JCheckBox jCheckBox029;
    private javax.swing.JCheckBox jCheckBox030;
    private javax.swing.JCheckBox jCheckBox031;
    private javax.swing.JCheckBox jCheckBox032;
    private javax.swing.JCheckBox jCheckBox033;
    private javax.swing.JCheckBox jCheckBox034;
    private javax.swing.JCheckBox jCheckBox035;
    private javax.swing.JCheckBox jCheckBox036;
    private javax.swing.JCheckBox jCheckBox06;
    private javax.swing.JCheckBox jCheckBox07;
    private javax.swing.JCheckBox jCheckBox08;
    private javax.swing.JCheckBox jCheckBox09;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox110;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOrga;
    private javax.swing.JTextField jTextFieldAcces;
    private javax.swing.JTextField jTextFieldDisc;
    private javax.swing.JTextField jTextFieldEnvo;
    private javax.swing.JTextField jTextFieldExt;
    private javax.swing.JTextField jTextFieldFiltro;
    private javax.swing.JTextField jTextFieldOrgPrev;
    private java.util.List<OrganizaPrev> list;
    private java.util.List<Atividade> listAtv;
    private javax.persistence.Query query;
    private javax.persistence.Query queryAtv;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


private void atualizaGrid(){
    String ejbql = "from OrganizaPrev";
         String ordem = "";
         if(JcbxOrdenar.getSelectedItem().toString().equals("Envolvidos")){
             ordem = "envolvidos";
         }else if(JcbxOrdenar.getSelectedItem().toString().equals("Discurso")){
             ordem = "discurso";
         }
         String filtro = jTextFieldFiltro.getText();
         if(filtro.length() > 0 && filtro != null ){
             ejbql += " where upper("+ordem+") like'"+filtro.toUpperCase()+"%' ";
         }
         ejbql += " order by " + ordem;
        System.out.println("EJBQL gerado: " + ejbql);
        query = entityManager.createQuery(ejbql);
        list.clear();
        list.addAll(query.getResultList());
        int row = list.size() - 1;
        jTableOrga.setRowSelectionInterval(row, row);
        jTableOrga.scrollRectToVisible(jTableOrga.getCellRect(row, row, true));
}
    
private boolean validaCampos(){
    return true;
}

private void trataEdicao(){
       jButtonCancelar.setEnabled(editando);
        jButtonGravar.setEnabled(editando);
        jButtonEditar.setEnabled(!editando);
        jButtonExcluir.setEnabled(!editando);
        jButtonFechar.setEnabled(!editando);
        jButtonNovo.setEnabled(!editando);
//        jButtonPrimeiro.setEnabled(!editando);
//        jButtonQuarto.setEnabled(!editando);
//        jButtonTerceiro.setEnabled(!editando);
//        jButtonSegundo.setEnabled(!editando);
        jButtonFiltrar.setEnabled(!editando);
        JcbxOrdenar.setEnabled(!editando);
        jTextFieldFiltro.setEnabled(!editando);
        jTableOrga.setEnabled(!editando);
        
//        jTextFieldFone.setEnabled(editando);
//        jTextFieldEmail.setEnabled(editando);
//        jTextFieldNome.setEnabled(editando);
}

private void pegaValorCheck(){
        String mensage = "";

        if (jCheckBox1.isSelected()) {
            mensage = mensage + " Ambiente virtual para inscrição, submissão e avaliação de trabalhos ";
        }
        if (jCheckBox2.isSelected()) {
            mensage = mensage + " NEAD/Moodle ";
        }
        if (jCheckBox3.isSelected()) {
            mensage = mensage + " canetas quadro branco/apagador ";
        }
        if (jCheckBox4.isSelected()) {
            mensage = mensage + " Reserva salas adequadas ";
        }
        if (jCheckBox5.isSelected()) {
            mensage = mensage + " Som ";
        }
        if (jCheckBox06.isSelected()) {
            mensage = mensage + " Colocação de Faixas ";
        }
        if (jCheckBox06.isSelected()) {
            mensage = mensage + " Operador de recursos audiovisuais ";
        }
    
        if (jCheckBox07.isSelected()) {
            mensage = mensage + " Texto de apresentação dos anais ";
        }
        if(jCheckBox08.isSelected()){
             mensage = mensage + " Instrumento de avaliação (pedagógica e satisfação)";
        }
        if(jCheckBox09.isSelected()){
            mensage = mensage + " Estrutura para apresentação de trabalhos ";
        }
        if(jCheckBox110.isSelected()){
             mensage = mensage + " Identificação da equipe organizadora (crachás) ";
        }
        if(jCheckBox011.isSelected()){
             mensage = mensage + " Vídeo institucional ";
        }
        if(jCheckBox012.isSelected()){
             mensage = mensage + " Cerimonial ";
        }
        if(jCheckBox013.isSelected()){
            mensage = mensage + " Solicitação de diárias/deslocamento ";
        }
        if(jCheckBox014.isSelected()){
            mensage = mensage + " Certificado dos palestrantes ";
        }
        if(jCheckBox015.isSelected()){
            mensage = mensage + " Espaço para parceiros ";
        }
        if(jCheckBox016.isSelected()){
            mensage = mensage + " Impressão de diário ";
        }
        if(jCheckBox018.isSelected()){
            mensage = mensage + " Reserva de hotel (se professor externo) ";
        }
        if(jCheckBox019.isSelected()){
            mensage = mensage + " Cobertura assessoria de imprensa ";
        }
        if(jCheckBox020.isSelected()){
            mensage = mensage + " Iluminação específica ";
        }
        if(jCheckBox021.isSelected()){
            mensage = mensage + " Banner da URCAMP ";
        }
         if(jCheckBox022.isSelected()){
             mensage = mensage + " Estrutura para exposições ";
         }
         if(jCheckBox023.isSelected()){
             mensage = mensage + " Brindes ";
         }
         if(jCheckBox024.isSelected()){
             mensage = mensage + " Coquetel ";
         }
         if(jCheckBox025.isSelected()){
             mensage = mensage + " Café e água ";
         }
         if(jCheckBox026.isSelected()){
             mensage = mensage + " Decoração ";
         }
         if(jCheckBox027.isSelected()){
             mensage = mensage + " Coffee break "; 
         }
         if(jCheckBox028.isSelected()){
             mensage = mensage + " Organização e composição da mesa ";
         }
         if(jCheckBox029.isSelected()){
             mensage = mensage + " Nacional ";
         }
          if(jCheckBox030.isSelected()){
              mensage = mensage + " RS ";
          }
          if(jCheckBox031.isSelected()){
              mensage = mensage + " Cidade "; 
          }
          if(jCheckBox032.isSelected()){
              mensage = mensage + " URCAMP ";
          }
          if(jCheckBox033.isSelected()){
             mensage = mensage + " Nacional ";
          }
          if(jCheckBox034.isSelected()){
              mensage = mensage + " Bagé ";
          }
          if(jCheckBox035.isSelected()){
              mensage = mensage + " Rio Grande do Sul ";
          }
          if(jCheckBox036.isSelected()){
              mensage = mensage + " País do visitante/palestrante ";
          }
       jTextFieldOrgPrev.setText(mensage);
    }



}
