/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import EntityManager.EntityManagerUtil;
import java.util.HashMap;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import modelo.bean.Setor;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author mateus
 */
public class FormCadastroSetor extends javax.swing.JDialog {
boolean editando;
//private String envolvido;
    /**
     * Creates new form FormCadastroSetor2
     */
    public FormCadastroSetor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("UrcampEventoEextensaoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("from Setor order by parceiroExterno");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        converterHora = new Utilitarias.ConverterHora();
        converterData1 = new Utilitarias.ConverterData();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        JcbxOrdenar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFiltro = new javax.swing.JTextField();
        jButtonFiltrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSetores = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskTime = null;
        try{
            maskTime = new javax.swing.text.MaskFormatter("##:##");
            maskTime.setPlaceholderCharacter('_');
        }catch(Exception e){

        }
        jTextFieldHorar = new javax.swing.JFormattedTextField(maskTime);
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLocalSet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskData = null;
        try {
            maskData = new javax.swing.text.MaskFormatter("##/##/####");
            maskData.setPlaceholderCharacter('_');
        } catch (Exception e){

        }
        jTextFieldDataSet = new javax.swing.JFormattedTextField(maskData);
        jTextFieldCheck = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanelCheck = new javax.swing.JPanel();
        jCheckBoxEdiuUrcamp = new javax.swing.JCheckBox();
        jCheckBoxNead = new javax.swing.JCheckBox();
        jCheckBoxCim = new javax.swing.JCheckBox();
        jCheckBoxAscom = new javax.swing.JCheckBox();
        jCheckBoxATI = new javax.swing.JCheckBox();
        jCheckBoxNadd = new javax.swing.JCheckBox();
        jCheckBoxProc = new javax.swing.JCheckBox();
        jCheckBoxJornalMin = new javax.swing.JCheckBox();
        jCheckBoxProad = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCentro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldParceiroEx = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonGravar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.green)); // NOI18N

        jLabel8.setText("Ordem:");

        JcbxOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro", "Titulo" }));
        JcbxOrdenar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JcbxOrdenarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JcbxOrdenarFocusLost(evt);
            }
        });

        jLabel9.setText("Filtro");

        jTextFieldFiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFiltroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFiltroFocusLost(evt);
            }
        });

        jButtonFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462404504_filter.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(JcbxOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButtonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFiltrar))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(JcbxOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, jTableSetores);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${envolvido}"));
        columnBinding.setColumnName("Envolvido");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${centro}"));
        columnBinding.setColumnName("Centro");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${campus}"));
        columnBinding.setColumnName("Campus");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${titulo}"));
        columnBinding.setColumnName("Titulo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${localsetor}"));
        columnBinding.setColumnName("Localsetor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${parceiroexterno}"));
        columnBinding.setColumnName("Parceiroexterno");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jTableSetores);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Evento"));

        jLabel6.setText("Horario:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableSetores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.horario}"), jTextFieldHorar, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(converterHora);
        bindingGroup.addBinding(binding);

        jTextFieldHorar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldHorarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldHorarFocusLost(evt);
            }
        });
        jTextFieldHorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorarActionPerformed(evt);
            }
        });

        jLabel4.setText("Titulo Evento:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableSetores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.titulo}"), jTextFieldTitulo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTituloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTituloFocusLost(evt);
            }
        });
        jTextFieldTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldTituloMouseClicked(evt);
            }
        });
        jTextFieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTituloKeyTyped(evt);
            }
        });

        jLabel7.setText("Local:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableSetores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.localsetor}"), jTextFieldLocalSet, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldLocalSet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLocalSetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLocalSetFocusLost(evt);
            }
        });
        jTextFieldLocalSet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldLocalSetKeyTyped(evt);
            }
        });

        jLabel5.setText("Data evento:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableSetores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.datsetor}"), jTextFieldDataSet, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(converterData1);
        bindingGroup.addBinding(binding);

        jTextFieldDataSet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDataSetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDataSetFocusLost(evt);
            }
        });

        jTextFieldCheck.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableSetores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.envolvido}"), jTextFieldCheck, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.green)); // NOI18N

        jPanelCheck.setBorder(javax.swing.BorderFactory.createTitledBorder("Envolvidos"));
        jPanelCheck.setForeground(java.awt.Color.green);

        jCheckBoxEdiuUrcamp.setText("EdiuUrcamp");
        jCheckBoxEdiuUrcamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEdiuUrcampActionPerformed(evt);
            }
        });

        jCheckBoxNead.setText("Nead");
        jCheckBoxNead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNeadActionPerformed(evt);
            }
        });

        jCheckBoxCim.setText("CIM");
        jCheckBoxCim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCimActionPerformed(evt);
            }
        });

        jCheckBoxAscom.setText("ASCOM");
        jCheckBoxAscom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAscomActionPerformed(evt);
            }
        });

        jCheckBoxATI.setText("ATI");
        jCheckBoxATI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxATIActionPerformed(evt);
            }
        });

        jCheckBoxNadd.setText("NADD");
        jCheckBoxNadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNaddActionPerformed(evt);
            }
        });

        jCheckBoxProc.setText("PROCJUR");
        jCheckBoxProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProcActionPerformed(evt);
            }
        });

        jCheckBoxJornalMin.setText("Jornal Minuano");
        jCheckBoxJornalMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxJornalMinActionPerformed(evt);
            }
        });

        jCheckBoxProad.setText("PROAD/RH/Financeiro");
        jCheckBoxProad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProadActionPerformed(evt);
            }
        });

        jLabel2.setText("Centro:");

        jComboBoxCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CCEA", "CCEHA", "CCS", "CCSA" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableSetores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.centro}"), jComboBoxCentro, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBoxCentro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxCentroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxCentroFocusLost(evt);
            }
        });

        jLabel1.setText("Campus:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Central(Bagé)", "Corujão(Bagé)", "Campus-Rural(Bagé)", "Intec(Bagé)", "Alegrete", "Santana Do Livramento", "São gabriel" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableSetores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.campus}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });

        jLabel3.setText("Parceiro externo:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableSetores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.parceiroexterno}"), jTextFieldParceiroEx, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldParceiroEx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParceiroExFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParceiroExFocusLost(evt);
            }
        });
        jTextFieldParceiroEx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldParceiroExKeyTyped(evt);
            }
        });

        jButton1.setText("Atividades");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCheckLayout = new javax.swing.GroupLayout(jPanelCheck);
        jPanelCheck.setLayout(jPanelCheckLayout);
        jPanelCheckLayout.setHorizontalGroup(
            jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCheckLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldParceiroEx, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCheckLayout.createSequentialGroup()
                        .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxATI)
                            .addComponent(jCheckBoxNadd)
                            .addComponent(jCheckBoxProc)
                            .addComponent(jCheckBoxAscom))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCheckLayout.createSequentialGroup()
                                .addComponent(jCheckBoxJornalMin)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelCheckLayout.createSequentialGroup()
                                .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxProad)
                                    .addComponent(jCheckBoxEdiuUrcamp)
                                    .addGroup(jPanelCheckLayout.createSequentialGroup()
                                        .addComponent(jCheckBoxNead)
                                        .addGap(33, 33, 33)
                                        .addComponent(jCheckBoxCim)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxCentro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanelCheckLayout.setVerticalGroup(
            jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckLayout.createSequentialGroup()
                .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCheckLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxNadd)
                            .addComponent(jCheckBoxNead)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxCim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxATI)
                            .addComponent(jCheckBoxProad)))
                    .addGroup(jPanelCheckLayout.createSequentialGroup()
                        .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCheckLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxEdiuUrcamp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxProc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCheckLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)))
                        .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxAscom)
                            .addComponent(jCheckBoxJornalMin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldParceiroEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanelCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462403813_close.png"))); // NOI18N
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldLocalSet, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldDataSet, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldHorar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(jTextFieldCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldDataSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldLocalSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldHorar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.green)); // NOI18N
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462402262_BT_save.png"))); // NOI18N
        jButtonGravar.setToolTipText("Grave aqui");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonGravar);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462402370_editor-trash-delete-recycle-bin-glyph.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Exclusão");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonExcluir);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462402556_add.png"))); // NOI18N
        jButtonNovo.setToolTipText("novo registro");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonNovo);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462402761_cancel-2.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonCancelar);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462403130_update.png"))); // NOI18N
        jButtonEditar.setToolTipText("Alterar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonEditar);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/1462403685_broom_stick_3.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar Campos");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonLimpar);

        jMenu1.setText("Relatorios");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Setores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Próxima tela");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
       dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int linhaClicada = jTableSetores.getSelectedRow();
        if(linhaClicada < 0){
            JOptionPane.showMessageDialog(null, "Selecione um campo para editar!");
        }else{
            editando = true;
            trataEdicao();
            jTextFieldTitulo.requestFocus();
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        editando = false;
        trataEdicao();
        atualizaGrid();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
         list.add((Setor) new Setor());
        int row = list.size() -1;
        jTableSetores.setRowSelectionInterval(row, row);
        editando = true;
        trataEdicao();
        jTextFieldTitulo.requestFocus();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (Utilitarias.Uteis.confirmar("Confirmar exclusao?")) {
            int linhaClicada = jTableSetores.getSelectedRow();
            if (linhaClicada < 0) {
                JOptionPane.showMessageDialog(null, "Selecione um registro para a excluão!");
            } else {
                try {

                    Setor obj = list.get(linhaClicada);
                    entityManager.getTransaction().begin();
                    entityManager.remove(obj);
                    entityManager.getTransaction().commit();
                    editando = false;
                    trataEdicao();
                    atualizaGrid();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao gravar" + e.getMessage());
                    if (entityManager.getTransaction().isActive() == false) {
                        entityManager.getTransaction().begin();
                    }
                    entityManager.getTransaction().rollback();
                    editando = false;
                    trataEdicao();
                }
            }

        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        if(validaCampos()){
            try{
                int linhaClicada = jTableSetores.getSelectedRow();
                Setor obj = list.get(linhaClicada);
                entityManager.getTransaction().begin();
                entityManager.persist(obj);
                entityManager.getTransaction().commit();
                editando = false;
                trataEdicao();
                atualizaGrid();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro ao gravar" + e.getMessage());
                if(entityManager.getTransaction().isActive()==false){
                    entityManager.getTransaction().begin();
                }
                entityManager.getTransaction().rollback();
                editando = false;
                atualizaGrid();
                trataEdicao();
            }
        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jTextFieldHorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHorarActionPerformed

    private void jCheckBoxNaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNaddActionPerformed
        pegaValorCheck();
    }//GEN-LAST:event_jCheckBoxNaddActionPerformed

    private void jCheckBoxEdiuUrcampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEdiuUrcampActionPerformed
     pegaValorCheck();
    }//GEN-LAST:event_jCheckBoxEdiuUrcampActionPerformed

    private void jCheckBoxAscomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAscomActionPerformed
      pegaValorCheck();
    }//GEN-LAST:event_jCheckBoxAscomActionPerformed

    private void jCheckBoxNeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNeadActionPerformed
     pegaValorCheck();
    }//GEN-LAST:event_jCheckBoxNeadActionPerformed

    private void jCheckBoxCimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCimActionPerformed
      pegaValorCheck();
    }//GEN-LAST:event_jCheckBoxCimActionPerformed

    private void jCheckBoxProadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProadActionPerformed
    pegaValorCheck();
     
    }//GEN-LAST:event_jCheckBoxProadActionPerformed

    private void jCheckBoxProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProcActionPerformed
        pegaValorCheck();
      
    }//GEN-LAST:event_jCheckBoxProcActionPerformed

    private void jCheckBoxJornalMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxJornalMinActionPerformed
     pegaValorCheck();
     
    }//GEN-LAST:event_jCheckBoxJornalMinActionPerformed

    private void jCheckBoxATIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxATIActionPerformed
       pegaValorCheck();
    }//GEN-LAST:event_jCheckBoxATIActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
       jTextFieldCheck.setText("");
       jTextFieldDataSet.setText("");
       jTextFieldHorar.setText("");
       jTextFieldLocalSet.setText("");
     //  jComboBoxCentro.setText("");
       jTextFieldParceiroEx.setText("");
        jTextFieldTitulo.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Utilitarias.Uteis.confirmar("Você já terminou o seu registro?")){
        JDialog form = new FormCadastroAtividades(null, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Cadastro De Atividades");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldTituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloMouseClicked

    private void jTextFieldTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTituloFocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldTituloFocusGained

    private void jTextFieldTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTituloFocusLost
       Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldTituloFocusLost

    private void jTextFieldLocalSetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLocalSetFocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldLocalSetFocusGained

    private void jTextFieldLocalSetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLocalSetFocusLost
       Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldLocalSetFocusLost

    private void jTextFieldDataSetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDataSetFocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldDataSetFocusGained

    private void jTextFieldDataSetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDataSetFocusLost
        Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldDataSetFocusLost

    private void jTextFieldHorarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldHorarFocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldHorarFocusGained

    private void jTextFieldHorarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldHorarFocusLost
      Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldHorarFocusLost

    private void jComboBoxCentroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCentroFocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jComboBoxCentroFocusGained

    private void jComboBoxCentroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxCentroFocusLost
     Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jComboBoxCentroFocusLost

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
       Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jTextFieldParceiroExFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParceiroExFocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldParceiroExFocusGained

    private void jTextFieldParceiroExFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParceiroExFocusLost
       Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldParceiroExFocusLost

    private void JcbxOrdenarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JcbxOrdenarFocusGained
       Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_JcbxOrdenarFocusGained

    private void JcbxOrdenarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JcbxOrdenarFocusLost
       Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_JcbxOrdenarFocusLost

    private void jTextFieldFiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFiltroFocusGained
        Utilitarias.Uteis.entraCampo(evt);
    }//GEN-LAST:event_jTextFieldFiltroFocusGained

    private void jTextFieldFiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFiltroFocusLost
       Utilitarias.Uteis.saiCampo(evt);
    }//GEN-LAST:event_jTextFieldFiltroFocusLost

    private void jTextFieldTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTituloKeyTyped
       Utilitarias.Uteis.limitaTamanhoCampo(evt, 40);
    }//GEN-LAST:event_jTextFieldTituloKeyTyped

    private void jTextFieldLocalSetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLocalSetKeyTyped
              Utilitarias.Uteis.limitaTamanhoCampo(evt, 40);

    }//GEN-LAST:event_jTextFieldLocalSetKeyTyped

    private void jTextFieldParceiroExKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldParceiroExKeyTyped
        Utilitarias.Uteis.limitaTamanhoCampo(evt, 40); // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParceiroExKeyTyped

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
       dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        JDialog form = new FormCadastroAtividades(null, true);
        form.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        form.setTitle("Cadastro De Atividades");
        form.setLocationRelativeTo(null);
        form.setResizable(false);
        form.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       dispose();
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
      
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       try {
		    EntityManager em = EntityManagerUtil.getEntityManager();
		    List<Setor> lista = em.createQuery("from Setor").getResultList();
		    HashMap<String, Object> parametros = new HashMap<String, Object>();
		    String relatorio = "/../home/mateus/Documentos/ATI/UrcampEventoEextensao/reportSetores.jasper";
		    JRDataSource dataSource = new JRBeanCollectionDataSource(lista);
		    JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, dataSource);
		    JDialog viewer = new JDialog(new javax.swing.JFrame(), "Visualização do Relátorio", true);
		    viewer.setSize(1024, 768);
		    viewer.setLocationRelativeTo(null);
		    JasperViewer jrviewer = new JasperViewer(impressao, true);
		    viewer.getContentPane().add(jrviewer.getContentPane());
		    viewer.setVisible(true);
		} catch (JRException ex) {
		    System.out.print("Erro: " + ex.getMessage());
                }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windown".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){             
                FormCadastroSetor dialog = new FormCadastroSetor(new javax.swing.JFrame(), true);
                 dialog.setLocationRelativeTo(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbxOrdenar;
    private Utilitarias.ConverterData converterData1;
    private Utilitarias.ConverterHora converterHora;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JCheckBox jCheckBoxATI;
    private javax.swing.JCheckBox jCheckBoxAscom;
    private javax.swing.JCheckBox jCheckBoxCim;
    private javax.swing.JCheckBox jCheckBoxEdiuUrcamp;
    private javax.swing.JCheckBox jCheckBoxJornalMin;
    private javax.swing.JCheckBox jCheckBoxNadd;
    private javax.swing.JCheckBox jCheckBoxNead;
    private javax.swing.JCheckBox jCheckBoxProad;
    private javax.swing.JCheckBox jCheckBoxProc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxCentro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelCheck;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSetores;
    private javax.swing.JTextField jTextFieldCheck;
    private javax.swing.JTextField jTextFieldDataSet;
    private javax.swing.JTextField jTextFieldFiltro;
    private javax.swing.JTextField jTextFieldHorar;
    private javax.swing.JTextField jTextFieldLocalSet;
    private javax.swing.JTextField jTextFieldParceiroEx;
    private javax.swing.JTextField jTextFieldTitulo;
    private java.util.List<Setor> list;
    private javax.persistence.Query query;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


private void atualizaGrid(){
     String ejbql = "from Setor";
         String ordem = "";
         if(JcbxOrdenar.getSelectedItem().toString().equals("Centro")){
             ordem = "centro";
         }else if(JcbxOrdenar.getSelectedItem().toString().equals("Titulo")){
             ordem = "titulo";
         }
         String filtro = jTextFieldFiltro.getText();
         if(filtro.length() > 0 && filtro != null ){
             ejbql += " where upper("+ordem+") like'"+filtro.toUpperCase()+"%' ";
         }
         ejbql += " order by " + ordem;
        System.out.println("EJBQL gerado: " + ejbql);
        query = entityManager.createQuery(ejbql);
        list.clear();
        list.addAll(query.getResultList());
        int row = list.size() - 1;
        jTableSetores.setRowSelectionInterval(row, row);
        jTableSetores.scrollRectToVisible(jTableSetores.getCellRect(row, row, true));
}
    
private boolean validaCampos(){
   
    if(!(jTextFieldCheck.getText().length() > 0 && jTextFieldCheck.getText() !=null)){
        JOptionPane.showMessageDialog(null, "Selecione um setor!!");
            jCheckBoxNadd.requestFocus();
            return false;
    }
    if(!(jTextFieldDataSet.getText().length() > 0 && jTextFieldDataSet.getText()!=null)){
        JOptionPane.showMessageDialog(null, "Informe a data atual!!");
        jTextFieldDataSet.requestFocus();
        return false;
    }
    if(!(jTextFieldHorar.getText().length() > 0 && jTextFieldHorar.getText()!=null)){
        JOptionPane.showMessageDialog(null, "Informe um horario!!");
        jTextFieldHorar.requestFocus();
        return false;
    }
    if(!(jTextFieldParceiroEx.getText().length() > 0 && jTextFieldParceiroEx.getText()!=null)){
        JOptionPane.showMessageDialog(null, "Um parceiro externo deve ser informado!!");
        jTextFieldParceiroEx.requestFocus();
        return false;
    }
    if(!(jTextFieldTitulo.getText().length() > 0 && jTextFieldTitulo.getText()!=null)){
         JOptionPane.showMessageDialog(null, "Um titulo de evendo deve ser informado!");
         jTextFieldTitulo.requestFocus();
        return false;
    }
    
     if(!(jTextFieldLocalSet.getText().length() > 0 && jTextFieldLocalSet.getText()!=null)){
         JOptionPane.showMessageDialog(null, "Um local do setor envolvido deve ser informado!!");
         jTextFieldLocalSet.requestFocus();
         return false;
     }
    return true;
}

private void trataEdicao(){
        jButtonCancelar.setEnabled(editando);
        jButtonGravar.setEnabled(editando);
        jButtonEditar.setEnabled(!editando);
        jButtonExcluir.setEnabled(!editando);
        jButtonFechar.setEnabled(!editando);
        jButtonNovo.setEnabled(!editando);
        jButtonFechar.setEnabled(!editando);

        
        jButtonFiltrar.setEnabled(!editando);
        JcbxOrdenar.setEnabled(!editando);
        jTextFieldFiltro.setEnabled(!editando);
        jTableSetores.setEnabled(!editando);
        
        jTextFieldDataSet.setEnabled(editando);
        jTextFieldHorar.setEnabled(editando);
        jTextFieldParceiroEx.setEnabled(editando);
        jTextFieldTitulo.setEnabled(editando);
        jComboBoxCentro.setEnabled(editando);
        jTextFieldLocalSet.setEnabled(editando);
}

private void pegaValorCheck(){
        String mensage = "";

        if (jCheckBoxATI.isSelected()) {
            mensage = mensage + " ATI ";
        }
        if (jCheckBoxNadd.isSelected()) {
            mensage = mensage + " NADD ";
        }
        if (jCheckBoxAscom.isSelected()) {
            mensage = mensage + " ASCOM ";
        }
        if (jCheckBoxCim.isSelected()) {
            mensage = mensage + " CIM ";
        }
        if (jCheckBoxEdiuUrcamp.isSelected()) {
            mensage = mensage + " EdiuUrcamp ";
        }
        if (jCheckBoxJornalMin.isSelected()) {
            mensage = mensage + " Jornal Minuano ";
        }
        if (jCheckBoxNead.isSelected()) {
            mensage = mensage + " NEAD ";
        }
        if (jCheckBoxProad.isSelected()) {
            mensage = mensage + " PROAD/RH/Financeiro ";
        }
        if (jCheckBoxProc.isSelected()) {
            mensage = mensage + " PROCJUR ";
        }

        jTextFieldCheck.setText(mensage);
    }
        
}
